/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class ViewMenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form ViewMenuAdmin
     */
    JLabel lbackground = new JLabel();
    public ViewMenuAdmin() {
        initComponents();
        setTitle ("Admin");
        setSize(500,400);
        setLocationRelativeTo(null);
        
        //add(lbackground);
        jLabel1.setForeground(Color.white);
        
//        lbackground.setIcon(new ImageIcon(getClass().getResource("Image/hotel2.jpg")));
//        lbackground.setBounds(0,0,400,400);
//        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDataPemesan = new javax.swing.JButton();
        jLogOut = new javax.swing.JButton();
        jDataPemesan1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ADMIN UPN HOMESTAY");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 80, 460, 44);

        jDataPemesan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jDataPemesan.setText("Data Pemesan");
        jDataPemesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataPemesanActionPerformed(evt);
            }
        });
        getContentPane().add(jDataPemesan);
        jDataPemesan.setBounds(140, 160, 150, 50);

        jLogOut.setText("Log Out");
        jLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(jLogOut);
        jLogOut.setBounds(380, 10, 90, 30);

        jDataPemesan1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jDataPemesan1.setText("Cek Kamar Kosong");
        jDataPemesan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataPemesan1ActionPerformed(evt);
            }
        });
        getContentPane().add(jDataPemesan1);
        jDataPemesan1.setBounds(140, 240, 150, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/Image/hotel2.jpg"))); // NOI18N
        jLabel2.setText("CEK kAMAR");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-270, -70, 910, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDataPemesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataPemesanActionPerformed
        // TODO add your handling code here:
        dispose();
        new ViewDataPemesan().setVisible(true);
    }//GEN-LAST:event_jDataPemesanActionPerformed

    private void jLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogOutActionPerformed
        // TODO add your handling code here:
         int dialogbutton=JOptionPane.showOptionDialog(this, "Yakin ingin keluar?", "Warning",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,null,null,null);
        if (dialogbutton==JOptionPane.YES_OPTION){
                
        dispose();
        new ViewLoginAdmin().setVisible(true);
        }
    
    
    }//GEN-LAST:event_jLogOutActionPerformed

    private void jDataPemesan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataPemesan1ActionPerformed
        dispose();
        new ViewCekKamarAdmin().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jDataPemesan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jDataPemesan;
    private javax.swing.JButton jDataPemesan1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jLogOut;
    // End of variables declaration//GEN-END:variables
}
