/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Fhrezha
 */
public class ViewBuatAkun extends javax.swing.JFrame {
ModelBuatAkun MdlAkun = new ModelBuatAkun();
JLabel lbackground = new JLabel();
    public ViewBuatAkun() {
        initComponents();
        setTitle ("CREATE ACCOUNT");
        setSize(550,400);
        
        setLocationRelativeTo(null);
        
//        add(lbackground);
//    
//    lbackground.setIcon(new ImageIcon(getClass().getResource("Image/hotel2.jpg")));
//    lbackground.setBounds(0,0,500,400);
//    
    jTextField1.setForeground(Color.black);
    jLabel1.setForeground(Color.black);
    jLabel2.setForeground(Color.black);
    jLabel3.setForeground(Color.black);
    jLabel4.setForeground(Color.black);
    jLabel5.setForeground(Color.black);
    jLabel6.setForeground(Color.black);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namalengkap = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        konfirm_pass = new javax.swing.JPasswordField();
        Back = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Membuat Akun");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 30, 210, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nama Lengkap");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 80, 110, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 210, 70, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Konfirmasi Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 250, 160, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("E-mail");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 170, 70, 17);
        getContentPane().add(namalengkap);
        namalengkap.setBounds(240, 80, 214, 26);
        getContentPane().add(email);
        email.setBounds(240, 160, 214, 28);

        Submit.setText("Simpan");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(280, 290, 90, 40);
        getContentPane().add(password);
        password.setBounds(240, 200, 214, 26);
        getContentPane().add(konfirm_pass);
        konfirm_pass.setBounds(240, 240, 214, 29);

        Back.setText("Kembali");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(160, 290, 90, 40);
        getContentPane().add(username);
        username.setBounds(240, 120, 214, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Username");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 120, 90, 14);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/Image/hotel13.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-580, -130, 1130, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        dispose();
        new ViewLoginClient().setVisible (true);
        
        
    }//GEN-LAST:event_BackActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
       
        String nama,username,email,password,konfirmasi_password;
        nama=namalengkap.getText().toString();
        username = this.username.getText().toString();
        email=this.email.getText().toString(); 
        password=this.password.getText().toString();
        konfirmasi_password=konfirm_pass.getText().toString();
       
        MdlAkun.akun (nama,username,email,password,konfirmasi_password);
        dispose();
        new ViewAkunClient(username).setVisible (true);
       
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBuatAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBuatAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBuatAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBuatAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBuatAkun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Submit;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField konfirm_pass;
    private javax.swing.JTextField namalengkap;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
