/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class ViewDataPemesan extends javax.swing.JFrame {
ModelCheckIn MdlCheckIn = new ModelCheckIn();
    /**
     * Creates new form ViewDataPemesan
     */
     private String checkIn;
     public ViewDataPemesan frame;
    public ViewDataPemesan() {
        initComponents();
        setTitle ("Data Pemesan");
        setSize(630,450);
        
        setLocationRelativeTo(null);
        this.frame = this;
        load_booking_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableBooking = new javax.swing.JTable();
        jBatalPesan = new javax.swing.JButton();
        jBack = new javax.swing.JButton();
        jCheckIn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jNoKtp = new javax.swing.JTextField();
        jNama = new javax.swing.JTextField();
        jJenisKamar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTglMasuk = new javax.swing.JTextField();
        jTglKeluar = new javax.swing.JTextField();
        chehckout = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Data Pemesan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        TableBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No KTP", "Nama", "Alamat", "No HP", "Jenis Kamar", "Tgl Masuk", "Tgl Keluar", "Status"
            }
        ));
        TableBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableBookingMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableBooking);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, 582, 151));

        jBatalPesan.setText("Batalkan Pemesanan");
        jBatalPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBatalPesanActionPerformed(evt);
            }
        });
        getContentPane().add(jBatalPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 170, 30));

        jBack.setText("Kembali");
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });
        getContentPane().add(jBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 90, 30));

        jCheckIn.setText("Check In");
        jCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckInActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 90, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("No KTP");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 257, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 295, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Jenis Kamar");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));
        getContentPane().add(jNoKtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 254, 159, -1));

        jNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNamaActionPerformed(evt);
            }
        });
        getContentPane().add(jNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 292, 159, -1));

        jJenisKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJenisKamarActionPerformed(evt);
            }
        });
        getContentPane().add(jJenisKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 330, 159, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Tgl Masuk");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 257, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Tgl Keluar");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 295, -1, -1));

        jTglMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTglMasukActionPerformed(evt);
            }
        });
        getContentPane().add(jTglMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 254, 150, -1));
        getContentPane().add(jTglKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 292, 150, -1));

        chehckout.setText("Check Out");
        chehckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chehckoutActionPerformed(evt);
            }
        });
        getContentPane().add(chehckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 100, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/Image/hotel10.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -60, 820, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
        // TODO add your handling code here:
        int dialogbutton=JOptionPane.showOptionDialog(this, "Yakin ingin kembali", "Warning",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,null,null,null);
        if (dialogbutton==JOptionPane.YES_OPTION){
            this.dispose();
            new ViewMenuAdmin().setVisible (true);
        }
    
    }//GEN-LAST:event_jBackActionPerformed

    private void TableBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableBookingMouseClicked
        int row = TableBooking.rowAtPoint(evt.getPoint());
        jNoKtp.setText(TableBooking.getValueAt(row, 0).toString());
        jNama.setText(TableBooking.getValueAt(row, 1).toString());
        jJenisKamar.setText(TableBooking.getValueAt(row, 4).toString());
        jTglMasuk.setText(TableBooking.getValueAt(row, 5).toString());
        jTglKeluar.setText(TableBooking.getValueAt(row, 6).toString());
        
    }//GEN-LAST:event_TableBookingMouseClicked

    private void jBatalPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBatalPesanActionPerformed
//        dispose();
//        new ViewBatalPesan().setVisible(true);
String no_ktp = jNoKtp.getText();
String jenis_kamar = jJenisKamar.getText();
        
        
                    KoneksiDatabase konek = new KoneksiDatabase();
                    konek.deleteData(no_ktp, frame);
                    konek.batalinPesan(no_ktp, jenis_kamar);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBatalPesanActionPerformed

    private void jCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckInActionPerformed
        // TODO add your handling code here:
        //String no_ktp,nama,jenis_kamar,tgl_masuk, tgl_keluar;
        
        String no_ktp = jNoKtp.getText();
        String nama = jNama.getText();
        String jenis_kamar = jJenisKamar.getText();
        String tgl_masuk = jTglMasuk.getText();
        String tgl_keluar = jTglKeluar.getText();
        //MdlReserved.pesan (no_ktp,nama,jenis_kamar,tgl_masuk,tgl_keluar);
       
       //public void pesan(String no_ktp, String nama, String jenis_kamar, String tgl_masuk, String tgl_keluar) {
                    Connection con;
                    con = new KoneksiDatabase().connect();
                    KoneksiDatabase konek = new KoneksiDatabase();
                    konek.updateStatus(no_ktp, nama,con,frame);

    }//GEN-LAST:event_jCheckInActionPerformed

    private void jTglMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTglMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTglMasukActionPerformed

    private void jNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNamaActionPerformed

    private void jJenisKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJenisKamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jJenisKamarActionPerformed

    private void chehckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chehckoutActionPerformed
        String no_ktp = jNoKtp.getText();
        String nama = jNama.getText();
        String jenis_kamar = jJenisKamar.getText();
        String tgl_masuk = jTglMasuk.getText();
        String tgl_keluar = jTglKeluar.getText();
        //MdlReserved.pesan (no_ktp,nama,jenis_kamar,tgl_masuk,tgl_keluar);
       
       //public void pesan(String no_ktp, String nama, String jenis_kamar, String tgl_masuk, String tgl_keluar) {
                    Connection con;
                    con = new KoneksiDatabase().connect();
                    KoneksiDatabase konek = new KoneksiDatabase();
                    konek.deleteStatus(no_ktp,con,frame);
                    konek.batalinPesan(no_ktp,jenis_kamar);
        // TODO add your handling code here:
    }//GEN-LAST:event_chehckoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDataPemesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDataPemesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDataPemesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDataPemesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDataPemesan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableBooking;
    private javax.swing.JToggleButton chehckout;
    private javax.swing.JButton jBack;
    private javax.swing.JButton jBatalPesan;
    private javax.swing.JButton jCheckIn;
    private javax.swing.JTextField jJenisKamar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jNama;
    private javax.swing.JTextField jNoKtp;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTglKeluar;
    private javax.swing.JTextField jTglMasuk;
    // End of variables declaration//GEN-END:variables

    private void load_booking_data() {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
       DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("No KTP");
        dtm.addColumn("Nama");
        dtm.addColumn("Alamat");
        dtm.addColumn("No HP");
        dtm.addColumn("Jenis Kamar");
        dtm.addColumn("Tgl Masuk");
        dtm.addColumn("Tgl Keluar");
        dtm.addColumn("Status");
        
        try {
            java.sql.Connection con; //METHOD MEMBUAT KONEKSI
            con = new KoneksiDatabase().connect();
            String sql = "SELECT * FROM `booking`";
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery(sql);
            while (rs.next()){
                dtm.addRow(new Object[]{
                    rs.getString("no_ktp"),
                    rs.getString("nama"),
                    rs.getString("alamat"),
                    rs.getString("no_hp"),
                    rs.getString("jenis_kamar"),
                    rs.getString("tgl_masuk"),
                    rs.getString("tgl_keluar"),
                    rs.getString("status"),
                    
                });
            }
            s.close();
            con.close();
           
            TableBooking.setModel(dtm);
        } catch (SQLException ex ) {
            Logger.getLogger(ViewDataPemesan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "You got an Error!", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    
    }
}
